server:
    port: 8080
    servlet:
        context-path: /identity

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/identity_db
        username: identity_user
        password: identity_password
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

jwt:
    secretKey: "df4c4cf9c3c03188e94d49062de808b7663d9dc50f77f80e8c8d38cec2a264d3"